/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsNumber,
  Min,
  Max,
  ValidateNested,
} from "class-validator";
import { FollowedCompanyUpdateManyWithoutStocksInput } from "./FollowedCompanyUpdateManyWithoutStocksInput";
import { Type } from "class-transformer";
import { NewsUpdateManyWithoutStocksInput } from "./NewsUpdateManyWithoutStocksInput";
import { PortfolioUpdateManyWithoutStocksInput } from "./PortfolioUpdateManyWithoutStocksInput";

@InputType()
class StockUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  symbolField?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  marketCap?: number | null;

  @ApiProperty({
    required: false,
    type: () => FollowedCompanyUpdateManyWithoutStocksInput,
  })
  @ValidateNested()
  @Type(() => FollowedCompanyUpdateManyWithoutStocksInput)
  @IsOptional()
  @Field(() => FollowedCompanyUpdateManyWithoutStocksInput, {
    nullable: true,
  })
  followedCompanies?: FollowedCompanyUpdateManyWithoutStocksInput;

  @ApiProperty({
    required: false,
    type: () => NewsUpdateManyWithoutStocksInput,
  })
  @ValidateNested()
  @Type(() => NewsUpdateManyWithoutStocksInput)
  @IsOptional()
  @Field(() => NewsUpdateManyWithoutStocksInput, {
    nullable: true,
  })
  newsItems?: NewsUpdateManyWithoutStocksInput;

  @ApiProperty({
    required: false,
    type: () => PortfolioUpdateManyWithoutStocksInput,
  })
  @ValidateNested()
  @Type(() => PortfolioUpdateManyWithoutStocksInput)
  @IsOptional()
  @Field(() => PortfolioUpdateManyWithoutStocksInput, {
    nullable: true,
  })
  portfolios?: PortfolioUpdateManyWithoutStocksInput;
}

export { StockUpdateInput as StockUpdateInput };
