/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsNumber,
  Min,
  Max,
  ValidateNested,
} from "class-validator";
import { FollowedCompanyCreateNestedManyWithoutStocksInput } from "./FollowedCompanyCreateNestedManyWithoutStocksInput";
import { Type } from "class-transformer";
import { NewsCreateNestedManyWithoutStocksInput } from "./NewsCreateNestedManyWithoutStocksInput";
import { PortfolioCreateNestedManyWithoutStocksInput } from "./PortfolioCreateNestedManyWithoutStocksInput";

@InputType()
class StockCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  symbolField?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  marketCap?: number | null;

  @ApiProperty({
    required: false,
    type: () => FollowedCompanyCreateNestedManyWithoutStocksInput,
  })
  @ValidateNested()
  @Type(() => FollowedCompanyCreateNestedManyWithoutStocksInput)
  @IsOptional()
  @Field(() => FollowedCompanyCreateNestedManyWithoutStocksInput, {
    nullable: true,
  })
  followedCompanies?: FollowedCompanyCreateNestedManyWithoutStocksInput;

  @ApiProperty({
    required: false,
    type: () => NewsCreateNestedManyWithoutStocksInput,
  })
  @ValidateNested()
  @Type(() => NewsCreateNestedManyWithoutStocksInput)
  @IsOptional()
  @Field(() => NewsCreateNestedManyWithoutStocksInput, {
    nullable: true,
  })
  newsItems?: NewsCreateNestedManyWithoutStocksInput;

  @ApiProperty({
    required: false,
    type: () => PortfolioCreateNestedManyWithoutStocksInput,
  })
  @ValidateNested()
  @Type(() => PortfolioCreateNestedManyWithoutStocksInput)
  @IsOptional()
  @Field(() => PortfolioCreateNestedManyWithoutStocksInput, {
    nullable: true,
  })
  portfolios?: PortfolioCreateNestedManyWithoutStocksInput;
}

export { StockCreateInput as StockCreateInput };
